//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HF_super_mart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Employee_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone_Number { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Job_Id { get; set; }
        public System.DateTime Hire_Date { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
