//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HF_super_mart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Invoice_Id { get; set; }
        public int Customer_Name { get; set; }
        public int Category_Name { get; set; }
        public int Product_Name { get; set; }
        public int Product_Price { get; set; }
        public Nullable<System.DateTime> Invoice_date { get; set; }
        public Nullable<System.TimeSpan> Invoice_time { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Price Price { get; set; }
    }
}
